#################################### shardingsphere 配置  ###########################################################
spring:
  # 配置说明地址 http://shardingsphere.apache.org/document/legacy/3.x/document/cn/manual/sharding-proxy/configuration/
  shardingsphere:
    # 数据库
    datasource:
      # 数据库的别名
      names: ds0
      ds0: # 主库1
        ###  数据源类别
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://146.56.192.87:3306/shardingsphere?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
        username: oyc
        password: 111111
    sharding:
      # 数据节点
      tables:
        user:
          actual-data-nodes: ds0.user_$->{0..9}
          table-strategy:
            inline:
              sharding-column: user_id  # 分表策略 其中user为逻辑表 分表主要取决于user_id行
              algorithm-expression: user_$->{user_id % 10}
          key-generator:
            column: user_id
            type: SNOWFLAKE
    props:
      # 打印SQL
      sql.show: true
      check:
        table:
          metadata: true
          # 是否在启动时检查分表元数据一致性
          enabled: true